# Generated by Django 3.1 on 2020-08-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='https://remotestance.com/blog/2612/'),
            preserve_default=False,
        ),
    ]
