# Generated by Django 3.1 on 2020-08-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=20200821, error_messages={'unique': 'This article already exists.'}, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
