# Generated by Django 3.1 on 2020-08-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newslistapp', '0002_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
