# Generated by Django 3.1 on 2020-08-22 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newslistapp', '0002_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_id',
            field=models.ForeignKey(default=20200821, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='ユーザー名'),
            preserve_default=False,
        ),
    ]
