# Generated by Django 3.1 on 2020-08-22 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newslistapp', '0003_article_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='user',
        ),
    ]
