# Generated by Django 3.1 on 2020-08-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslistapp', '0004_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(error_messages={'unique': 'This article already exists.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(),
        ),
    ]
