# Generated by Django 3.1 on 2020-08-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslistapp', '0006_article_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
