# Generated by Django 3.1 on 2020-08-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslistapp', '0007_auto_20200823_1409'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_booking'),
        ),
    ]
