# Generated by Django 3.1 on 2020-08-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslistapp', '0008_auto_20200823_1613'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='unique_booking',
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_booking'),
        ),
    ]
